### ISSUE TITLE
Change Max Speed on Ninebot One E

### ISSUE THREAD

**Issue by ILYA2606** [fgorina/9BMetrics#1]
Changing max speed is not working. Ninebot One E on 1.3.5 limiting max speed on ~22 km/h. I set max speed on 30 km/h via 9Metrics (TestMode), reset Ninebot One, but it's not works - limit also ~22 km/h :(

**Comment by fgorina** [comment]
About Max speed, efectively it is set (you may read it and returns the new value) but has no effect :)

Also no ida if it is possible to change serial number and if serial numbers have some checksum but may be interesting if max speed is controlled via serial number.

I knbow you may change the serial number but I am not very sure which values are OK.

There is some information abiur all which I have been able to get in http://www.gorina.es/9BMetrics/ http://www.gorina.es/9BMetrics/

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com
