### ISSUE TITLE
KingSong/Gotway total distance

### ISSUE THREAD

**Issue by ILYA2606** [fgorina/9BMetrics#7]
On KS/Gotway wrong calculating total distance. 
130 real km = 376045570.0 in app.
`let totalDistance = Double( (Int(buffer[6]) * 256 + Int(buffer[7]))*65536 + (Int(buffer[8]) * 256 + Int(buffer[9])))`

Tests:
On my tests KS14 rides 137km (by official app metrics).
Value of buffer:
buffer[6] = 2
buffer[7] = 0
buffer[8] = 106
buffer[9] = 22

Gotway MSuper V3 rides 8.4km
Value of buffer:
buffer[6] = 64
buffer[7] = 0
buffer[8] = 28
buffer[9] = 32

**Comment by fgorina** [comment]
The distance problem was solved. It produced this problem. Hope you have last version, may you confirm this?

Is a problem with the order of the values. If is last version will see if in KS14 is in diferent order than in KS16

Paco

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com

**Comment by ILYA2606** [comment]
I have last commit from multiwheel branch.
In Appstore_3.0 this problem has been fixed. Thanks!
