### ISSUE TITLE
Gotway temperature

### ISSUE THREAD

**Issue by ILYA2606** [fgorina/9BMetrics#8]
On Gotway (exclude MCM4) wrong calculating temperature. Tested on ACM, MSuper V3, Monster.

219 value app ≈ 20 °C

**Comment by fgorina** [comment]
Coud be 21,3 ºC?

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com

**Comment by ILYA2606** [comment]
Somewhere about.

buffer[12] = 245
buffer[13] = 74

Some wrong on line:
`let temperature = Double(Int(buffer[12]) * 256 + Int(buffer[13])) / 340.0 + 35.0 // Very strange`

I'm waiting for a report on the tests of my application, this will help to quickly fix this problem.

**Comment by ILYA2606** [comment]
Test:
buffer[12] = 247
buffer[13] = 160
Real temperature: 28.8 °C

**Comment by fgorina** [comment]
I have some strange readings in Gotway. They go form 227.032353 to 35.017647 and back.

That is the code in WheelLog which I used

mTemperature = (int) Math.round(((((data[12] * 256) + data[13]) / 340.0) + 35) * 100);

It is in Java and data is a byte[]

Soin principle byte in Java is signed.

So let's supose that we must use signed and not unsigned values
Probably : 

247*256 + 160 -> 63392 -> -2976

t = (-2976 / 340) + 25 = 26,25

It seems quite reasonable. 

I have tested with some logs and is possible.
I continue to have some spurious data but could be other type of errors.
Try to change temperature computation to

`                var intValue = Int(buffer[12]) * 256 + Int(buffer[13])
                
                if intValue >= 32768 {
                    intValue = intValue - 65536
                }
                
                let temperature = Double(intValue) / 340.0 + 35.0 // Seems 0 value is around 35ºC
`

I don't have the means to test it fast but if it you can test it perfect

**Comment by fgorina** [comment]
I think I have it solved.I posted it to the GitHub comment

Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158

**Comment by ILYA2606** [comment]
Nice!
